name: Dev

on:
 workflow_call
 
jobs:

 ReplaceTokens:
  uses: ./.github/workflows/TaskGroups/ReplaceTokens.yml
  with:
   target_environment: 'Dev'
  

 DeployToDev:
  needs: ReplaceTokens
  uses: ./.github/workflows/TaskGroups/Deploy.yml
  with:
   target_environment: 'Dev'
  
