name: Dacpac Deployment

on:
 workflow_call:
  inputs:
  
   SQLServer:
    required: true
    type: string

   ConnectionString:
    required: true
    type: string
    
   DacpacPackagePath:
    required: true
    type: string
  
jobs:
  DacpacDeployment:
    runs-on: [self-hosted, windows, x64]
  
    - name: Azure SQL Deploy (dacpac, file, folder)
      # You may pin to the exact commit or the version.
      #uses: XLipcak/sql-action@1b2b1ea66beb232831e97be2be8382be8f006840
      uses: XLipcak/sql-action@v1.0.5
      with:
          server-name: $ {{ inputs.SQLServer }}
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: $ {{ inputs.ConnectionString }}
          # Path to DACPAC file. *.dacpac or a folder to deploy
          dacpac-package: $$ {{ inputs.DacpacPackagePath }}
          
          # Path to SQL script file. *.sql or a folder to deploy
          # sql-file: # optional
          # Path to SQL folder to deploy
          # sql-folder: # optional
          # In case DACPAC option is selected, additional SqlPackage.exe arguments that will be applied. When SQL query option is selected, additional sqlcmd.exe arguments will be applied.
          # arguments: # optional
