name: Deploy

on:
 workflow_call:
  inputs:
   target_environment:
    required: true
    type: string
    
jobs:

 UploadArtifacts:
 
  runs-on: [self-hosted, windows, x64]
  steps:  
   - uses: actions/upload-artifact@v3.1.2
     with:
      name: artifacts
      path: MyArtifacts/
   
 Deploy:
  needs: UploadArtifacts
  runs-on: [self-hosted, windows, x64]
  
  steps:
  
  - name: Deploy To Dev
    if: inputs.target_environment == 'Dev'
    uses: actions/download-artifact@v3
    with: 
     name: artifacts
     path: 'C:\Users\nourhan.obada\Environments\Dev'
  
  - name: Deploy To QA
    if: inputs.target_environment == 'QA'
    uses: actions/download-artifact@v3
    with: 
     name: artifacts
     path: 'C:\Users\nourhan.obada\Environments\QA'
   
  - name: Deploy To Prod
    if: inputs.target_environment == 'Prod'
    uses: actions/download-artifact@v3
    with: 
     name: artifacts
     path: 'C:\Users\nourhan.obada\Environments\Prod'
 
  
  
  
    
