name: DeployDev

on:
 workflow_call:
  inputs:
   target_environment:
    required: true
    type: string
    
jobs:

 ReplaceTokens: 
 
  uses: ./.github/workflows/ReplaceTokens.yml
  with:
   target_environment: ${{ inputs.target_environment }}
   
 UploadArtifacts:
  
  needs: ReplaceTokens
  runs-on: [self-hosted, windows, x64]
  steps:  
   - uses: actions/upload-artifact@v3.1.2
     with:
      name: artifacts
      path: MyArtifacts/
   
 Deploy:
 
  uses: ./.github/workflows/Deploy.yml
  with:
   target_environment: ${{ inputs.target_environment }}
     
