name: Dev

on:
 workflow_call:
  inputs:
   target_environment:
    required: true
    type: string
  
jobs:

 DeployToDev:
 
  uses: ./.github/workflows/Deploy.yml
  with:
   target_environment: ${{ inputs.target_environment }}  
