name: Dev

#on:
 #workflow_call:
  #inputs:
   #target_environment:
    #required: true
    #type: string
  
#jobs:

 #DeployToDev:
 
  #uses: ./.github/workflows/Deploy.yml
  #with:
   #target_environment: ${{ inputs.target_environment }}  
   
on:
 workflow_dispatch 
 
jobs:

 CheckoutRepo:
 
  runs-on: [self-hosted, windows, x64]
  #environment: Dev
  steps:
    - uses: actions/checkout@v3.3.0
    
 ReplaceTokens:
  needs: CheckoutRepo

  runs-on: [self-hosted, windows, x64]
  environment: Dev
  
  env: 
   WelcomeMessage: ${{vars.WELCOMEMESSAGE}}
   Name: ${{vars.NAME}}
   Age: ${{vars.AGE}}
   Profession: ${{vars.PROFESSION}}
   
  steps:
  
  - name: Replace tokens
    uses: cschleiden/replace-tokens@v1.2
    with: 
     tokenPrefix: '{{'
     tokenSuffix: '}}'
     files: 'MyArtifacts/*'
   

 DeployToDev:
  needs: ReplaceTokens
  uses: ./.github/workflows/Deploy.yml
  with:
   target_environment: 'Dev'
  
