name: Main

on:
 workflow_dispatch 
 
jobs:

 CheckoutRepo:
 
  runs-on: [self-hosted, windows, x64]
  steps:
    - uses: actions/checkout@v3.3.0
    
 
 DeployToDev:
  needs: CheckoutRepo
  uses: ./.github/workflows/Dev.yml
  with:
   target_environment: 'Dev'
    
   
 DeployToQA:
  
  needs: CheckoutRepo
  uses: ./.github/workflows/QA.yml
  with:
   target_environment: 'QA'
   
 #DeployToProd:
  
  #needs: CheckoutRepo
  #uses: ./.github/workflows/Prod.yml
  #with:
   #target_environment: 'Prod'
