name: Main

on:
 workflow_dispatch 
 
jobs:

 CheckoutRepo:
 
  runs-on: [self-hosted, windows, x64]
  
  steps:
      
    - uses: actions/checkout@v3
    
    - uses: actions/upload-artifact@v3.1.2
      with:
       name: Artifacts
       path: MyArtifacts/
       
 ReplaceTokens:
 
  needs: CheckoutRepo
  
  runs-on: [self-hosted, windows, x64]
  
  environment: Dev
     
  steps:
      
    - shell: cmd 
      run: mkdir Downloads
      
    - uses: ./.github/workflows/ReplaceTokens.yml
      
    - uses: actions/download-artifact@v3.0.2
      with:
       name: Artifacts
       path: Downloads
