name: Main

on:
 workflow_dispatch 
 
jobs:

 CheckoutRepo:
 
  runs-on: [self-hosted, windows, x64]
  steps:
    - uses: actions/checkout@v3.3.0
    
    
 UploadArtifacts:
  
  needs: CheckoutRepo
  runs-on: [self-hosted, windows, x64]
  steps:
  
   - shell: cmd 
     run: mkdir Uploads
      
   - uses: actions/upload-artifact@v3.1.2
     with:
      name: artifacts
      path: Uploads/

    
 
 ReplaceTokens:
 
  needs: UploadArtifacts
  uses: ./.github/workflows/ReplaceTokens.yml
  with:
   target_environment: 'Dev'
   
   

 DeployToDev:
  
  needs: ReplaceTokens
  uses: ./.github/workflows/Deploy.yml
  with:
   target_environment: 'Dev'
   
