name: Main

on:
 workflow_dispatch 
 
jobs:

 CheckoutRepo:
 
  runs-on: [self-hosted, windows, x64]
  steps:
      
    - uses: actions/checkout@v3.3.0
    
    #- uses: ./.github/workflows/ReplaceTokens.yml
    
 
 ReplaceTokens:
 
  needs: CheckoutRepo
  environment: Dev
  runs-on: [self-hosted, windows, x64]
  steps:
  
  - name: Replace tokens
    uses: cschleiden/replace-tokens@v1.2
    with: 
     tokenPrefix: '{{'
     tokenSuffix: '}}'
     files: 'MyArtifacts/Artifactone'

 
 UploadArtifacts:

  needs: ReplaceTokens
  runs-on: [self-hosted, windows, x64]
  steps:
    
    - uses: actions/upload-artifact@v3.1.2
      with:
       name: Artifacts
       path: MyArtifacts/
       
       
 DownloadArtifacts:
 
  needs: UploadArtifacts
  runs-on: [self-hosted, windows, x64] 
  steps:
      
    - shell: cmd 
      run: mkdir Downloads
      
    - uses: actions/download-artifact@v3.0.2
      with:
       name: Artifacts
       path: Downloads
