name: QA

on:
 workflow_call
 
jobs:

 ReplaceTokens:
  uses: ./.github/workflows/ReplaceTokens.yml
  with:
   target_environment: 'QA'
  

 DeployToDev:
  needs: ReplaceTokens
  uses: ./.github/workflows/Deploy.yml
  with:
   target_environment: 'QA'
  
