name: Release

on: 
 workflow_dispatch
 
jobs:
 
 #Azure Login     
AzureLogin:
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        #environment: 'AzureStack'
        
 #This task to replace our variables
 ReplaceTokens:
  
  runs-on: [self-hosted, windows, x64]
  environment: Dev
  
  env: 
   WelcomeMessage: ${{vars.WELCOMEMESSAGE}}
   Name: ${{vars.NAME}}
   Age: ${{vars.AGE}}
   Profession: ${{vars.PROFESSION}}
   
  steps:
  
  - name: Replace tokens
    uses: cschleiden/replace-tokens@v1.2
    with: 
     tokenPrefix: '{{'
     tokenSuffix: '}}'
     files: 'MyArtifacts/*'
     
#Stop needed Sitecoe services     
 StopService:
  needs: ReplaceTokens
  runs-on: [self-hosted, windows, x64]
  steps:
      - name: Stop Service
        shell: powershell
        run: |
            Stop-AzWebApp -ResourceGroupName "${{ ResourceGroupName }}" -Name "${{ AppService }}"
            
            
 #Upload DoZen Artifacts
 UploadArtifacts:
  needs: StopService
  runs-on: [self-hosted, windows, x64]
  steps:  
   - uses: actions/upload-artifact@v3.1.2
     with:
      name: artifacts
      path: MyArtifacts/
   
#Copy Artifacts   
 CopyToPath:
  needs: UploadArtifacts
  runs-on: [self-hosted, windows, x64]
  
  steps:
  
  - name: Deploy To Dev
    uses: actions/download-artifact@v3
    with: 
     name: artifacts
     path: 'C:\Users\....\Environments\Dev'
 
 #Start services
 StartService:
  needs: CopyToPath
  runs-on: [self-hosted, windows, x64]
  steps:
      - name: Start Service
        shell: powershell
        run: |
            Start-AzWebApp -ResourceGroupName "${{ ResourceGroupName }}" -Name "${{ AppService }}"
            
 #Deploy Sitecore Content items using Webdeploy     
 Webdeploy:
  needs: StartService
  runs-on: [self-hosted, windows, x64]
  steps:
      - shell: powershell
        run: |
            C:\LocalPublishWebDeploy\LocalPublishWebDeploy.ps1  -PackagePath "${{Path}}"
            
 #Deploy DoZen Custom DBs
 DacPacDeployment:
  needs: Webdeploy
  runs-on: [self-hosted, windows, x64]
  steps:
    - name: Azure SQL Deploy (dacpac, file, folder)
      uses: XLipcak/sql-action@v1.0.5
      with:
          server-name: $ {{ SQLServer }}
          connection-string: $ {{ ConnectionString }}
          dacpac-package: $$ {{ DacpacPackagePath }}
         
#Deploy DoZen artifacts to App Services
DeployToAppService:
  - name: Deploy to Azure Web App
    id: deploy-to-webapp
    uses: azure/webapps-deploy@v2
    with:
        app-name: RTXTest
        publish-profile: ${{ secrets.RTXTEST_PUBLISHPROFILE }}
        package: C:\DoZen-PKG\Latest\DoZen-Core\dozen\deploy\platform
