name: TestSeparateStages

on:
 workflow_dispatch 
 
jobs:

 DeployToDev:

  uses: ./.github/workflows/Dev.yml
    
   
   
 DeployToQA:
  
  needs: DeployToDev
  uses: ./.github/workflows/QA.yml
  
   
