name: TestSeparateStages

on:
 workflow_dispatch 
 
jobs:

 DeployToDev:

  uses: ./.github/workflows/Dev.yml
  with:
   target_environment: 'Dev'
    
   
   
 DeployToQA:
  
  needs: DeployToDev
  uses: ./.github/workflows/QA.yml
  with:
   target_environment: 'QA'
  
   
