name: TestSeparateStages

on:
 workflow_dispatch 
 
jobs:

 ApprovalDev:
 
  runs-on: [self-hosted, windows, x64]
  environment: Dev
  

 DeployToDev:
  needs: ApprovalDev
  uses: ./.github/workflows/Dev.yml
  with:
   target_environment: 'Dev'
    
   
   
 #DeployToQA:
  
  #needs: DeployToDev
  #uses: ./.github/workflows/QA.yml
  #with:
   #target_environment: 'QA'
  
   
